name: Script

on:
  schedule:
#     - cron: '0 12 * * *'
      - cron: '0,5,10,15,20,25,30,35,40,45,50,55  * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
        
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
    
      run: |
        python3 ./main.py 
