name: 'GitHub Actions Weather Bot'

on:
  push:
    branches: [ main ]
    
  schedule:
#     - cron: '0 12 * * *'
      - cron: '0 22 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SetUpPython
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install requests

    - name: Run 
      run: |
        python3 ./main.py 
